
name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: vednig/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v4
      with:
        name: web_browser
        path: src/dist/windows
